-- DDL: Create tables for account and transaction lineage demo
-- Database: DB2/PostgreSQL compatible

CREATE TABLE IF NOT EXISTS ACCOUNT_SUMMARY (
    ACCOUNT_NUMBER    BIGINT          NOT NULL,
    CUSTOMER_NAME     VARCHAR(40)     NOT NULL,
    ACCOUNT_TYPE      VARCHAR(5)      NOT NULL,
    BALANCE           DECIMAL(15, 2)  NOT NULL DEFAULT 0.00,
    OPEN_DATE         DATE            NOT NULL,
    STATUS_CODE       CHAR(2)         NOT NULL DEFAULT 'AC',
    CREDIT_LIMIT      DECIMAL(13, 2)  NOT NULL DEFAULT 0.00,
    BRANCH_CODE       CHAR(4),
    PRODUCT_CODE      VARCHAR(6),
    LAST_UPDATED      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ACCOUNT_SUMMARY PRIMARY KEY (ACCOUNT_NUMBER)
);

CREATE TABLE IF NOT EXISTS TRANSACTION_DETAIL (
    TRANSACTION_ID    VARCHAR(12)     NOT NULL,
    ACCOUNT_NUMBER    BIGINT          NOT NULL,
    TRANS_DATE        DATE            NOT NULL,
    TRANS_TIME        CHAR(6)         NOT NULL,
    TRANS_TYPE        VARCHAR(4)      NOT NULL,
    AMOUNT            DECIMAL(13, 2)  NOT NULL,
    CURRENCY_CODE     CHAR(3)         NOT NULL DEFAULT 'USD',
    MERCHANT_ID       VARCHAR(20),
    MERCHANT_CATEGORY VARCHAR(4),
    AUTH_CODE         VARCHAR(6),
    STATUS            CHAR(2)         NOT NULL DEFAULT 'VA',
    RISK_SCORE        DECIMAL(5, 2)   NOT NULL DEFAULT 0.00,
    LOADED_AT         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TRANSACTION_DETAIL PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_TRANS_ACCOUNT FOREIGN KEY (ACCOUNT_NUMBER)
        REFERENCES ACCOUNT_SUMMARY(ACCOUNT_NUMBER)
);

CREATE INDEX IF NOT EXISTS IDX_TRANS_ACCOUNT
    ON TRANSACTION_DETAIL (ACCOUNT_NUMBER, TRANS_DATE);

CREATE INDEX IF NOT EXISTS IDX_TRANS_DATE
    ON TRANSACTION_DETAIL (TRANS_DATE);

-- Monthly reporting view (populated by create_report.sql)
-- MONTHLY_REPORT is defined in create_report.sql
