-- load_accounts.sql
-- Loads ACCOUNT_SUMMARY from the COBOL PROG001 output file (account_output.dat)
-- Source: ACCOUNT.OUTPUT.FILE (DD: OUTFILE from JCL STEP010)

LOAD DATA
    INFILE 'account_output.dat'
    INTO TABLE ACCOUNT_SUMMARY
    FIELDS TERMINATED BY '|'
    LINES TERMINATED BY '\n'
    (
        ACCOUNT_NUMBER  POSITION(1:10)    INTEGER EXTERNAL,
        CUSTOMER_NAME   POSITION(11:50)   CHAR,
        ACCOUNT_TYPE    POSITION(51:55)   CHAR,
        BALANCE         POSITION(56:72)   DECIMAL EXTERNAL,
        OPEN_DATE       POSITION(73:80)   DATE FORMAT 'YYYYMMDD',
        STATUS_CODE     POSITION(81:82)   CHAR,
        CREDIT_LIMIT    POSITION(83:97)   DECIMAL EXTERNAL,
        BRANCH_CODE     POSITION(98:101)  CHAR,
        PRODUCT_CODE    POSITION(102:107) CHAR
    )
    LOG FILE 'load_accounts.log'
    BAD FILE 'load_accounts.bad'
    DISCARD FILE 'load_accounts.dsc'
    DISCARD MAX 100;
